#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:

#  ca:
#    command: sh -c 'fabric-ca-server start -d --ca.name default'

#  api:
#    environment:
#      - ENROLL_ID=cn=${ENROLL_ID},${LDAP_BASE_DN}

  ldap-service:
    container_name: ldap.${ORG:-org1}.${DOMAIN:-example.com}
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=${ORG:-org1}
      - LDAP_DOMAIN=${ORG:-org1}.${DOMAIN:-example.com}
      - LDAP_ADMIN_PASSWORD=${ENROLL_SECRET}
    volumes:
      - ./data/ldap/${ORG:-org1}/database:/var/lib/ldap
      - ./data/ldap/${ORG:-org1}/config:/etc/ldap/slapd.d
      - ./data/ldap/${ORG:-org1}/certs:/container/service/slapd/assets/certs

  ldapadmin-service:
    container_name: ldapadmin.${ORG:-org1}.${DOMAIN:-example.com}
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap.${ORG:-org1}.${DOMAIN:-example.com}
      - PHPLDAPADMIN_HTTPS=false
#      - PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME=ca.crt
    image: osixia/phpldapadmin
    ports:
      - ${LDAPADMIN_HTTPS_PORT:-6443}:443
      - ${LDAPADMIN_HTTP_PORT:-6080}:80
#    volumes:
#      - ./data/ldap/certs:/container/service/phpldapadmin/assets/apache2/certs
    depends_on:
      - ldap-service

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK_NAME:-fabric-starter}_default