#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:

  pre-install:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug



  post-install:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug
    command: container-scripts/install-default-chaincodes.sh
#    command: "sh"


  cli.orderer:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug


